USE dwwm5;

SET storage_engine=myISAM;

CREATE TABLE IF NOT EXISTS tableA (id INT);
CREATE TABLE IF NOT EXISTS tableB (id INT);
CREATE TABLE IF NOT EXISTS tableC (id INT);

CREATE TABLE IF NOT EXISTS tablef (id INT NOT NULL) ENGINE = CSV;

ALTER TABLE tableB ENGINE=InnoDB;